version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: iosifpolodashvili/med_comfort:latest
    restart: always
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - web
volumes:
  data:
  static:
  media: